export const START_PLURAL_JOBS_FETCH = "START_PLURAL_JOBS_FETCH"
export const PLURAL_JOBS_FETCH_SUCCESS = "PLURAL_JOBS_FETCH_SUCCESS"
export const PLURAL_JOBS_FETCH_FAILURE = "PLURAL_JOBS_FETCH_FAILURE"
export const START_SINGLE_JOB_FETCH = 'START_SINGLE_JOB_FETCH'
export const SINGLE_JOB_FETCH_SUCCESS = "SINGLE_JOB_FETCH_SUCCESS"
export const SINGLE_JOB_FETCH_FAILURE = "SINGLE_JOB_FETCH_FAILURE"
export const VIEW_SINGLE_JOB = "VIEW_SINGLE_JOB"
export const VIEW_ALL_JOBS = "VIEW_ALL_JOBS"
export const SET_LOCATION = "SET_LOCATION"
export const SET_DESCRIPTION = "SET_DESCRIPTION"
export const SET_FULLTIME = "SET_FULLTIME"

